baseURL = 'https://vulpine.house'
languageCode = 'en-us'
title = 'The Fridge'
author = 'Síle Ekaterin Liszka'
theme = 'clean'
disableKinds = ['RSS', 'sitemap']

[Params]
Fediverse = ['https://social.treehouse.systems/@VulpineAmethyst']