[[main]]
identifier = 'home'
name       = 'Home'
url        = '/'
weight     = 1

[[main]]
identifier = 'about'
name       = 'About'
url        = '/about'
weight     = 2

[[main]]
identifier = 'translations'
name       = 'Translations'
url        = '/translations'
weight     = 3

[[main]]
identifier = 'recipes'
name       = 'Recipes'
url        = '/recipe'
weight     = 4

[[main]]
identifier = 'commissions'
name       = 'Commissions'
url        = 'commissions'
weight     = 5

[[main]]
identifier = 'system'
name       = 'System Reference'
url        = 'system'
weight     = 6

[[main]]
identifier = 'links'
name       = 'Links'
url        = 'links'
weight     = 7

