baseURL = 'https://vulpine.house'
languageCode = 'en-us'
title = 'The Fridge'
author = 'Síle Ekaterin Liszka'
theme = 'clean'

[[menu.main]]
identifier = 'home'
name       = 'Home'
url        = '/'
weight     = 1

[[menu.main]]
identifier = 'links'
name       = 'Links'
url        = 'links'
weight     = 2

[[menu.main]]
identifier = 'commissions'
name       = 'Commissions'
url        = 'commissions'
weight     = 3

[[menu.main]]
identifier = 'system'
name       = 'System Reference'
url        = 'system'
weight     = 4

[[menu.main]]
identifier = 'wishlists'
name       = 'Wishlists'
url        = 'wishlists'
weight     = 5
